Add a recipe for elk (https://sourceforge.net/projects/elk/)
An all-electron full-potential linearised augmented-planewave (FP-LAPW) code. Designed to be as developer friendly as possible so that new developments in the field of density functional theory (DFT) can be added quickly and reliably.

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Try with dynamic linking

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Use dynamic linking for lapack and blas

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Build the vendored dependencies. No dynamic linking

Do not build for OSX for now

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Convert the recipe to v2 (rattler-build)

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

elk: Update to 10.2.4

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

There is no make.def in elk v10.x

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Add make.inc with all the settings. It overwrites the default one before build

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Add make.inc with all the settings. It overwrites the default one before build

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Add libxc 6.x as a host requirement

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Delete meta.yaml

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Disable libxc usage.

The linking fails with:
```
libxcf03.f90:(.text+0x944): undefined reference to `libxc_free'
/home/mgrigorov/git/bioconda/elk/.pixi/envs/default/bin/../lib/gcc/aarch64-conda-linux-gnu/14.2.0/../../../../aarch64-conda-linux-gnu/bin/ld: libxcf03.f90:(.text+0x97c): undefined reference to `libxc_free'
/home/mgrigorov/git/bioconda/elk/.pixi/envs/default/bin/../lib/gcc/aarch64-conda-linux-gnu/14.2.0/../../../../aarch64-conda-linux-gnu/bin/ld: libxcf03.f90:(.text+0x9a0): undefined reference to `libxc_free'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:230: elk] Error 1
make[1]: Leaving directory '/home/mgrigorov/git/bioconda/elk/elk-10.2.4/src'
make: *** [Makefile:7: all] Error 2
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Add $PREFIX/lib to the library path

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Try with LDFLAGS instead

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Stub wannier too

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Add openmp to host requirements too

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>