Different approach to patch.
Previous attempt broke with clang:

x86_64-conda-linux-gnu-cc -o openemacs openemacs.c -g -O0 -Wall -Wextra -Werror -W -pedantic -std=c11 -Wformat=2 -Wswitch-default -Wunused
openemacs.c:137:137: error: initializer-string for array of 'char' truncates NUL terminator but destination lacks 'nonstring' attribute (3 chars into 2 available) [-Werror=unterminated-string-initialization]
  137 |     { .file_match = PYTHON_SYNTAX_HIGHLIGHT_FILE_EXTENSIONS, .keywords = PYTHON_SYNTAX_HIGHLIGHT_KEYWORDS, .single_line_comment_start = #0, .multi_line_comment_start = , .multi_line_comment_end =  },
      |                                                                                                                                         ^~~~~
 cc1: all warnings being treated as errors