see if prefix wildcard needed to avoid compile syntax error
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=149271&view=logs&j=10bda42a-d420-5c28-a43f-bc4e66405e5c&t=bef775d0-a1a2-55a3-9721-17147029baf0&l=13918

~~~
*** Error compiling '/tmp/pip-unpacked-wheel-_dk22q8p/leo/plugins/test/syntax_error_plugin.py'...
    File "/tmp/pip-unpacked-wheel-_dk22q8p/leo/plugins/test/syntax_error_plugin.py", line 10
      a = # This is the syntax error
                                   ^
  SyntaxError: invalid syntax
~~~