add setuptools to test-requires
azure-pipeline builds fail with:

import: 'cysgp4'
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/cysgp4_1574983520696/test_tmp/run_test.py", line 2, in <module>
    import cysgp4
  File "/home/conda/staged-recipes/build_artifacts/cysgp4_1574983520696/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.7/site-packages/cysgp4/__init__.py", line 6, in <module>
    from .helpers import *
  File "/home/conda/staged-recipes/build_artifacts/cysgp4_1574983520696/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.7/site-packages/cysgp4/helpers.py", line 4, in <module>
    from pkg_resources import resource_stream
ModuleNotFoundError: No module named 'pkg_resources'