esys-escript (#8796)
* esys-escript

esys-escript

* Add files via upload

* Delete meta.yaml

* Delete build.sh

* Delete LICENSE-2.0.txt

* Update build.sh

* Update meta.yaml

* Update meta.yaml

* Update meta.yaml

* Update meta.yaml

Added in svn

* Update build.sh

Bug: Wrong python version

* Update build.sh

Bug: python version in b2, added trilinos and escript build recipe

* Update build.sh

* Update build.sh

But: Changed python root in the boost bootstrap

* Update build.sh

Bug: Trilinos could not locate boost dir

* Update build.sh

* Update build.sh

Bug: Boost didn't build the correct boost python library

* Update meta.yaml

bug: pyconfig

* Update meta.yaml

* Update meta.yaml

error: could not resolve packages

* Update meta.yaml

error: could not resolve packages

* Update meta.yaml

Bug: syntax (which passed the lintian) still confused the buildbot

* Update meta.yaml

openblas

* Update meta.yaml

* Update build.sh

* Update meta.yaml

* Update meta.yaml

openblas fix

* Update build.sh

* Update build.sh

* Update build.sh

Bug: Trilinos could not find cholmod

* Update build.sh

Bug fix: Turning off trilinos TPL cholmod

* Update meta.yaml

* Windows build recipe

* Update meta.yaml

Removed  skips

* Update meta.yaml

* Update meta.yaml

* Update meta.yaml

* Update build.sh

bug: escript python

* Update build.sh

bug: escript python lib

* Update build.sh

* Update build.sh

Bug: removed tpls from trilinos

* Update build.sh

Bug: Syntax error

* Update build.sh

trying something

* Update build.sh

* Update meta.yaml

bug: scons version

* Update build.sh

Bug: Scons could not locate the c++ compiler for some reason? Have manually specified the location.

* Update build.sh

* Update build.sh

Bug: Make scons output more detailed error information

* Update build.sh

Bug: Syntax

* Update build.sh

Bug: escript could not locate the boost python library

* Update build.sh

* Update build.sh

Turning trilinos off temporarily

* Update build.sh

* Update build.sh

syntax

* Update build.sh

Turning Trilinos back on.

* Update meta.yaml

fixing bug: RPATH

* Update build.sh

Bug: openmp flag

* Update meta.yaml

bug: package

* Update build.sh

bug

* Update meta.yaml

Bug: Another RPATH error.

* Update meta.yaml

* Update build.sh

* Update meta.yaml

* Update meta.yaml

Linter picked up a problem

* Update meta.yaml

* Update build.sh

* Update meta.yaml

Lint

* Update recipes/esys-escript/meta.yaml

Co-Authored-By: Uwe L. Korn <xhochy@users.noreply.github.com>

* Update meta.yaml

* Update meta.yaml

* Delete LICENSE-2.0.txt

* Update meta.yaml

Various changes

* Update build.sh

Various changes

* Delete bld.bat

* Update meta.yaml

* Update meta.yaml

Switched to tarball.

* Update meta.yaml

* Update build.sh

Fixed bug: The builder could not locate the license file inside the tarball.

* Update build.sh

Bug: Test failed because the linker could not find one of the libraries.

* Update meta.yaml

Removed the openmp package

* Update meta.yaml

Missed one

* Update meta.yaml

Bug: Linking error (gnu compiler but llvm openmp)

* Update build.sh

unnecessary linker flag (-lomp)

* Update meta.yaml

* Update build.sh

* Update meta.yaml

Various changes

* Update meta.yaml

* Update meta.yaml

Syntax