Add pip as a build requirement
Cicle-CI failed due to there being no module named pip:

Downloading
https://pypi.io/packages/source/j/json_tricks/json_tricks-3.11.0.tar.gz
Success
Extracting download
source tree in:
/home/conda/feedstock_root/build_artifacts/json_tricks_1530561676515/work
/home/conda/feedstock_root/build_artifacts/json_tricks_1530561676515/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python:
No module named pip
Traceback (most recent call last):
    File "/home/conda/.ci_support/build_all.py", line 83, in <module>
        build_all(args.recipes_dir, args.arch)
    File "/home/conda/.ci_support/build_all.py", line 73, in build_all
        conda_build.api.build(list(d.keys()), config=config)
    File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
        notest=notest, need_source_download=need_source_download, variants=variants)
    File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
        notest=notest,
    File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1417, in build
        utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
    File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 310, in check_call_env
        return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
    File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 290, in _func_defaulting_env_to_os_environ
        raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/conda/feedstock_root/build_artifacts/json_tricks_1530561676515/work/conda_build.sh']' returned non-zero exit status 1.
Exited with code 1